#!/bin/bash

if [[ ! -e "$PWD/.rmtrash.log" ]]
then
	echo 1 > "$PWD/.rmtrash.log" 
fi

if [[ $# -gt 1 ]]
then
	echo "The number of arguments must be 1."
	exit 1
fi

if [[ ! -f $1 ]]
then
	echo "File not found."
	exit 1
fi

path="$HOME/.trash"
path_log="$HOME/.trash.log"

if [[ ! -d $path ]]
then
	mkdir "$path"
fi

count=$(cat "$PWD/.rmtrash.log")
ln "$PWD/$1" "$path/$count"
tmp="$PWD/$1"
tmp_ln="$path/$count"
touch "$tmp_ln"
(( count=count+1 ))
echo "$count" > "$PWD/.rmtrash.log"
rm "$tmp"
echo "$tmp $tmp_ln" >> "$path_log"
