#!/bin/bash

path="$HOME/.trash"
path_log="$HOME/.trash.log"
if [[ $# -ne 1 ]]
then
	echo "The number of arguments must be 1."
	exit 1
fi

if [[ ! -d $path ]]
then
	echo "$path: directory not fount"
	exit 1
fi

if [[ ! -e $path_log ]]
then
	echo "File trash.log doesn't exist"
	exit 1
fi

if [[ $(grep -E "$1 " "$path_log") == "" ]]
then
	echo "$1 not founded in trash.log"
	exit 1
fi

echo "$(grep -E "/$1" $path_log)" |
while read line;
do
	file_path=$(echo "$line" | awk '{print $1}')
	file_link=$(echo "$line" | awk '{print $2}')
	read -p "Restore $file_path? (y/n)" ans <&1
	
	case $ans in
		"" | "y")
			path2=$(echo "file_path" | awk -F"/$1" '{print $1}')
			if [[ ! -d $path2 ]]
			then
				echo "Directory $path2 doesn't exist anymore, file will be restored in $HOME"
				if [[ -f $file_path ]]
				then
					read -p "File $file_path exists in directory, choose different name: " name <&1
					ln "$file_link" "$HOME/$name"
					rm "$file_link"
				else
					ln "$file_link" "$HOME/$1"
					rm "$file_link"
				fi
			else
				if [[ -f $file_path ]]
				then
					read -p "File $file_path exists in directory, choose different name: " name <&1
					ln "$file_link" "$path2/$name"
					rm "$file_link"
				else
					ln "$file_link" "$path2/$1"
					rm "$file_link"
				fi
			fi
			grep -Ev "$file_link" "$path_log" > .untrash_tmp.log
			cat .untrash_tmp.log > "$dir_log"
			rm .untrash_tmp.log
			;;
		*)
			continue
			;;
	esac
done
